# Generated by Django 5.0 on 2023-12-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.TextField()),
                ('taskpriority', models.TextField()),
                ('taskdate', models.DateField()),
            ],
        ),
    ]
